In [1]:
pip install pandas numpy matplotlib seaborn missingno

Requirement already satisfied: pandas in d:\da projects\logistics-analytics-dashboard\venv\lib\site-packages (2.3.3)
Requirement already satisfied: numpy in d:\da projects\logistics-analytics-dashboard\venv\lib\site-packages (2.2.6)
Requirement already satisfied: matplotlib in d:\da projects\logistics-analytics-dashboard\venv\lib\site-packages (3.10.9)
Requirement already satisfied: seaborn in d:\da projects\logistics-analytics-dashboard\venv\lib\site-packages (0.13.2)
Collecting missingno
  Downloading missingno-0.5.2-py3-none-any.whl (8.7 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in d:\da projects\logistics-analytics-dashboard\venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in d:\da projects\logistics-analytics-dashboard\venv\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: pytz>=2020.1 in d:\da projects\logistics-analytics-dashboard\venv\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: packaging>=20.0 in d:\da projects\logistics-analytics-dashboard\venv\lib\site-packages (from matplotlib) (26.2)
Requirement already satisfied: cycler>=0.10 in d:\da projects\logistics-analytics-dashboard\venv\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in d:\da projects\logistics-analytics-dashboard\venv\lib\site-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in d:\da projects\logistics-analytics-dashboard\venv\lib\site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: contourpy>=1.0.1 in d:\da projects\logistics-analytics-dashboard\venv\lib\site-packages (from matplotlib) (1.3.2)
Requirement already satisfied: pyparsing>=3 in d:\da projects\logistics-analytics-dashboard\venv\lib\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: pillow>=8 in d:\da projects\logistics-analytics-dashboard\venv\lib\site-packages (from matplotlib) (12.2.0)
Collecting scipy
  Using cached scipy-1.15.3-cp310-cp310-win_amd64.whl (41.3 MB)
Requirement already satisfied: six>=1.5 in d:\da projects\logistics-analytics-dashboard\venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Installing collected packages: scipy, missingno
Successfully installed missingno-0.5.2 scipy-1.15.3
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 23.0.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
pip freeze > requirements.txt

Note: you may need to restart the kernel to use updated packages.

In [5]:
import pandas as pd

customers = pd.read_csv("D:/DA Projects/Logistics-Analytics-Dashboard/data/raw/olist_customers_dataset.csv")
orders = pd.read_csv("D:/DA Projects/Logistics-Analytics-Dashboard/data/raw/olist_orders_dataset.csv")
order_items = pd.read_csv("D:/DA Projects/Logistics-Analytics-Dashboard/data/raw/olist_order_items_dataset.csv")
payments = pd.read_csv("D:/DA Projects/Logistics-Analytics-Dashboard/data/raw/olist_order_payments_dataset.csv")
reviews = pd.read_csv("D:/DA Projects/Logistics-Analytics-Dashboard/data/raw/olist_order_reviews_dataset.csv")
products = pd.read_csv("D:/DA Projects/Logistics-Analytics-Dashboard/data/raw/olist_products_dataset.csv")
sellers = pd.read_csv("D:/DA Projects/Logistics-Analytics-Dashboard/data/raw/olist_sellers_dataset.csv")
category = pd.read_csv("D:/DA Projects/Logistics-Analytics-Dashboard/data/raw/product_category_name_translation.csv")

In [6]:
datasets = {
    "customers": customers,
    "orders": orders,
    "order_items": order_items,
    "payments": payments,
    "reviews": reviews,
    "products": products,
    "sellers": sellers,
    "category": category
}

for name, df in datasets.items():
    print("\n" + "="*50)
    print(name.upper())
    print("="*50)
    print("Shape:", df.shape)
    print(df.head())

==================================================
CUSTOMERS
==================================================
Shape: (99441, 5)
                        customer_id                customer_unique_id  \
0  06b8999e2fba1a1fbc88172c00ba8bc7  861eff4711a542e4b93843c6dd7febb0
1  18955e83d337fd6b2def6b18a428ac77  290c77bc529b7ac935b93aa66c333dc3
2  4e7b3e00288586ebd08712fdd0374a03  060e732b5b29e8181a18229c7b0b2b5e
3  b2b6027bc5c5109e529d4dc6358b12c3  259dac757896d24d7702b9acbbff3f3c
4  4f2d8ab171c80ec8364f7c12e35b23ad  345ecd01c38d18a9036ed96c73b8d066

   customer_zip_code_prefix          customer_city customer_state
0                     14409                 franca             SP
1                      9790  sao bernardo do campo             SP
2                      1151              sao paulo             SP
3                      8775        mogi das cruzes             SP
4                     13056               campinas             SP

==================================================
ORDERS
==================================================
Shape: (99441, 8)
                           order_id                       customer_id  \
0  e481f51cbdc54678b7cc49136f2d6af7  9ef432eb6251297304e76186b10a928d
1  53cdb2fc8bc7dce0b6741e2150273451  b0830fb4747a6c6d20dea0b8c802d7ef
2  47770eb9100c2d0c44946d9cf07ec65d  41ce2a54c0b03bf3443c3d931a367089
3  949d5b44dbf5de918fe9c16f97b45f8a  f88197465ea7920adcdbec7375364d82
4  ad21c59c0840e6cb83a9ceb5573f8159  8ab97904e6daea8866dbdbc4fb7aad2c

  order_status order_purchase_timestamp    order_approved_at  \
0    delivered      2017-10-02 10:56:33  2017-10-02 11:07:15
1    delivered      2018-07-24 20:41:37  2018-07-26 03:24:27
2    delivered      2018-08-08 08:38:49  2018-08-08 08:55:23
3    delivered      2017-11-18 19:28:06  2017-11-18 19:45:59
4    delivered      2018-02-13 21:18:39  2018-02-13 22:20:29

  order_delivered_carrier_date order_delivered_customer_date  \
0          2017-10-04 19:55:00           2017-10-10 21:25:13
1          2018-07-26 14:31:00           2018-08-07 15:27:45
2          2018-08-08 13:50:00           2018-08-17 18:06:29
3          2017-11-22 13:39:59           2017-12-02 00:28:42
4          2018-02-14 19:46:34           2018-02-16 18:17:02

  order_estimated_delivery_date
0           2017-10-18 00:00:00
1           2018-08-13 00:00:00
2           2018-09-04 00:00:00
3           2017-12-15 00:00:00
4           2018-02-26 00:00:00

==================================================
ORDER_ITEMS
==================================================
Shape: (112650, 7)
                           order_id  order_item_id  \
0  00010242fe8c5a6d1ba2dd792cb16214              1
1  00018f77f2f0320c557190d7a144bdd3              1
2  000229ec398224ef6ca0657da4fc703e              1
3  00024acbcdf0a6daa1e931b038114c75              1
4  00042b26cf59d7ce69dfabb4e55b4fd9              1

                         product_id                         seller_id  \
0  4244733e06e7ecb4970a6e2683c13e61  48436dade18ac8b2bce089ec2a041202
1  e5f2d52b802189ee658865ca93d83a8f  dd7ddc04e1b6c2c614352b383efe2d36
2  c777355d18b72b67abbeef9df44fd0fd  5b51032eddd242adc84c38acab88f23d
3  7634da152a4610f1595efa32f14722fc  9d7a1d34a5052409006425275ba1c2b4
4  ac6c3623068f30de03045865e4e10089  df560393f3a51e74553ab94004ba5c87

   shipping_limit_date   price  freight_value
0  2017-09-19 09:45:35   58.90          13.29
1  2017-05-03 11:05:13  239.90          19.93
2  2018-01-18 14:48:30  199.00          17.87
3  2018-08-15 10:10:18   12.99          12.79
4  2017-02-13 13:57:51  199.90          18.14

==================================================
PAYMENTS
==================================================
Shape: (103886, 5)
                           order_id  payment_sequential payment_type  \
0  b81ef226f3fe1789b1e8b2acac839d17                   1  credit_card
1  a9810da82917af2d9aefd1278f1dcfa0                   1  credit_card
2  25e8ea4e93396b6fa0d3dd708e76c1bd                   1  credit_card
3  ba78997921bbcdc1373bb41e913ab953                   1  credit_card
4  42fdf880ba16b47b59251dd489d4441a                   1  credit_card

   payment_installments  payment_value
0                     8          99.33
1                     1          24.39
2                     1          65.71
3                     8         107.78
4                     2         128.45

==================================================
REVIEWS
==================================================
Shape: (100000, 7)
                          review_id                          order_id  \
0  7bc2406110b926393aa56f80a40eba40  73fc7af87114b39712e6da79b0a377eb
1  80e641a11e56f04c1ad469d5645fdfde  a548910a1c6147796b98fdf73dbeba33
2  228ce5500dc1d8e020d8d1322874b6f0  f9e4b658b201a9f2ecdecbb34bed034b
3  e64fb393e7b32834bb789ff8bb30750e  658677c97b385a9be170737859d3511b
4  f7c4243c7fe1938f181bec41a392bdeb  8e6bfb81e283fa7e4f11123a3fb894f1

   review_score review_comment_title  \
0             4                  NaN
1             5                  NaN
2             5                  NaN
3             5                  NaN
4             5                  NaN

                              review_comment_message review_creation_date  \
0                                                NaN  2018-01-18 00:00:00
1                                                NaN  2018-03-10 00:00:00
2                                                NaN  2018-02-17 00:00:00
3              Recebi bem antes do prazo estipulado.  2017-04-21 00:00:00
4  Parabéns lojas lannister adorei comprar pela I...  2018-03-01 00:00:00

  review_answer_timestamp
0     2018-01-18 21:46:59
1     2018-03-11 03:05:13
2     2018-02-18 14:36:24
3     2017-04-21 22:02:06
4     2018-03-02 10:26:53

==================================================
PRODUCTS
==================================================
Shape: (32951, 9)
                         product_id  product_category_name  \
0  1e9e8ef04dbcff4541ed26657ea517e5             perfumaria
1  3aa071139cb16b67ca9e5dea641aaa2f                  artes
2  96bd76ec8810374ed1b65e291975717f          esporte_lazer
3  cef67bcfe19066a932b7673e239eb23d                  bebes
4  9dc1a7de274444849c219cff195d0b71  utilidades_domesticas

   product_name_lenght  product_description_lenght  product_photos_qty  \
0                 40.0                       287.0                 1.0
1                 44.0                       276.0                 1.0
2                 46.0                       250.0                 1.0
3                 27.0                       261.0                 1.0
4                 37.0                       402.0                 4.0

   product_weight_g  product_length_cm  product_height_cm  product_width_cm
0             225.0               16.0               10.0              14.0
1            1000.0               30.0               18.0              20.0
2             154.0               18.0                9.0              15.0
3             371.0               26.0                4.0              26.0
4             625.0               20.0               17.0              13.0

==================================================
SELLERS
==================================================
Shape: (3095, 4)
                          seller_id  seller_zip_code_prefix  \
0  3442f8959a84dea7ee197c632cb2df15                   13023
1  d1b65fc7debc3361ea86b5f14c68d2e2                   13844
2  ce3ad9de960102d0677a81f5d0bb7b2d                   20031
3  c0f3eea2e14555b6faeea3dd58c1b1c3                    4195
4  51a04a8a6bdcb23deccc82b0b80742cf                   12914

         seller_city seller_state
0           campinas           SP
1         mogi guacu           SP
2     rio de janeiro           RJ
3          sao paulo           SP
4  braganca paulista           SP

==================================================
CATEGORY
==================================================
Shape: (71, 2)
    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto
3         cama_mesa_banho                bed_bath_table
4        moveis_decoracao               furniture_decor

In [7]:
def quality_report(df):
    return pd.DataFrame({
        "Column": df.columns,
        "Missing Values": df.isnull().sum().values,
        "Data Type": df.dtypes.values,
        "Unique Values": [df[col].nunique() for col in df.columns]
    })

In [8]:
quality_report(orders)

                          Column  Missing Values Data Type  Unique Values
0                       order_id               0    object          99441
1                    customer_id               0    object          99441
2                   order_status               0    object              8
3       order_purchase_timestamp               0    object          98875
4              order_approved_at             160    object          90733
5   order_delivered_carrier_date            1783    object          81018
6  order_delivered_customer_date            2965    object          95664
7  order_estimated_delivery_date               0    object            459

In [9]:
for name, df in datasets.items():
    print(f"\n{name}")
    display(quality_report(df))

customers

                     Column  Missing Values Data Type  Unique Values
0               customer_id               0    object          99441
1        customer_unique_id               0    object          96096
2  customer_zip_code_prefix               0     int64          14994
3             customer_city               0    object           4119
4            customer_state               0    object             27

orders

                          Column  Missing Values Data Type  Unique Values
0                       order_id               0    object          99441
1                    customer_id               0    object          99441
2                   order_status               0    object              8
3       order_purchase_timestamp               0    object          98875
4              order_approved_at             160    object          90733
5   order_delivered_carrier_date            1783    object          81018
6  order_delivered_customer_date            2965    object          95664
7  order_estimated_delivery_date               0    object            459

order_items

                Column  Missing Values Data Type  Unique Values
0             order_id               0    object          98666
1        order_item_id               0     int64             21
2           product_id               0    object          32951
3            seller_id               0    object           3095
4  shipping_limit_date               0    object          93318
5                price               0   float64           5968
6        freight_value               0   float64           6999

payments

                 Column  Missing Values Data Type  Unique Values
0              order_id               0    object          99440
1    payment_sequential               0     int64             29
2          payment_type               0    object              5
3  payment_installments               0     int64             24
4         payment_value               0   float64          29077

reviews

                    Column  Missing Values Data Type  Unique Values
0                review_id               0    object          99173
1                 order_id               0    object          99441
2             review_score               0     int64              5
3     review_comment_title           88285    object           4600
4   review_comment_message           58247    object          36921
5     review_creation_date               0    object            637
6  review_answer_timestamp               0    object          99010

products

                       Column  Missing Values Data Type  Unique Values
0                  product_id               0    object          32951
1       product_category_name             610    object             73
2         product_name_lenght             610   float64             66
3  product_description_lenght             610   float64           2960
4          product_photos_qty             610   float64             19
5            product_weight_g               2   float64           2204
6           product_length_cm               2   float64             99
7           product_height_cm               2   float64            102
8            product_width_cm               2   float64             95

sellers

                   Column  Missing Values Data Type  Unique Values
0               seller_id               0    object           3095
1  seller_zip_code_prefix               0     int64           2246
2             seller_city               0    object            611
3            seller_state               0    object             23

category

                          Column  Missing Values Data Type  Unique Values
0          product_category_name               0    object             71
1  product_category_name_english               0    object             71

In [10]:
for name, df in datasets.items():
    print(
        f"{name}: {df.duplicated().sum()} duplicate rows"
    )

customers: 0 duplicate rows
orders: 0 duplicate rows
order_items: 0 duplicate rows
payments: 0 duplicate rows
reviews: 0 duplicate rows
products: 0 duplicate rows
sellers: 0 duplicate rows
category: 0 duplicate rows

In [11]:
date_cols = [
    'order_purchase_timestamp',
    'order_approved_at',
    'order_delivered_carrier_date',
    'order_delivered_customer_date',
    'order_estimated_delivery_date'
]

for col in date_cols:
    orders[col] = pd.to_datetime(
        orders[col],
        errors='coerce'
    )

In [12]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  datetime64[ns]
 4   order_approved_at              99281 non-null  datetime64[ns]
 5   order_delivered_carrier_date   97658 non-null  datetime64[ns]
 6   order_delivered_customer_date  96476 non-null  datetime64[ns]
 7   order_estimated_delivery_date  99441 non-null  datetime64[ns]
dtypes: datetime64[ns](5), object(3)
memory usage: 6.1+ MB

In [13]:
orders["delivery_days"] = (
    orders["order_delivered_customer_date"]
    - orders["order_purchase_timestamp"]
).dt.days

In [14]:
orders["estimated_days"] = (
    orders["order_estimated_delivery_date"]
    - orders["order_purchase_timestamp"]
).dt.days

In [15]:
orders["delay_days"] = (
    orders["order_delivered_customer_date"]
    - orders["order_estimated_delivery_date"]
).dt.days

In [16]:
orders["is_late"] = (
    orders["delay_days"] > 0
).astype(int)

In [17]:
orders[
    [
        "delivery_days",
        "estimated_days",
        "delay_days",
        "is_late"
    ]
].describe()

       delivery_days  estimated_days    delay_days       is_late
count   96476.000000    99441.000000  96476.000000  99441.000000
mean       12.094086       23.403958    -11.876881      0.065717
std         9.551746        8.829562     10.183854      0.247789
min         0.000000        1.000000   -147.000000      0.000000
25%         6.000000       18.000000    -17.000000      0.000000
50%        10.000000       23.000000    -12.000000      0.000000
75%        15.000000       28.000000     -7.000000      0.000000
max       209.000000      155.000000    188.000000      1.000000

In [19]:
orders[
[
"delivery_days",
"estimated_days",
"delay_days",
"is_late"
]
].describe()

       delivery_days  estimated_days    delay_days       is_late
count   96476.000000    99441.000000  96476.000000  99441.000000
mean       12.094086       23.403958    -11.876881      0.065717
std         9.551746        8.829562     10.183854      0.247789
min         0.000000        1.000000   -147.000000      0.000000
25%         6.000000       18.000000    -17.000000      0.000000
50%        10.000000       23.000000    -12.000000      0.000000
75%        15.000000       28.000000     -7.000000      0.000000
max       209.000000      155.000000    188.000000      1.000000

In [20]:
orders["is_late"].value_counts()

is_late
0    92906
1     6535
Name: count, dtype: int64