In [1]:
import pandas as pd

fact = pd.read_csv(
    "../data/processed/fact_orders.csv"
)

print(fact.shape)

(99441, 16)

In [2]:
features = [
    "payment_value",
    "freight_value",
    "order_value",
    "item_count"
]

X = fact[features]

y = fact["is_late"]

In [6]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [7]:
print(y.value_counts())
print(y.value_counts(normalize=True))

is_late
0    92906
1     6535
Name: count, dtype: int64
is_late
0    0.934283
1    0.065717
Name: proportion, dtype: float64

In [8]:
from sklearn.model_selection import train_test_split

features = [
    "payment_value",
    "freight_value",
    "order_value",
    "item_count"
]

X = fact[features]
y = fact["is_late"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print(X_train.shape)
print(X_test.shape)

(79552, 4)
(19889, 4)

In [10]:
fact_ml = fact.copy()

fact_ml = fact_ml.dropna(
    subset=[
        "payment_value",
        "freight_value",
        "order_value",
        "item_count",
        "is_late"
    ]
)

print(fact_ml.shape)

(98665, 16)

In [11]:
features = [
    "payment_value",
    "freight_value",
    "order_value",
    "item_count"
]

X = fact_ml[features]

y = fact_ml["is_late"]

In [12]:
print(X.isnull().sum())

payment_value    0
freight_value    0
order_value      0
item_count       0
dtype: int64

In [13]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [14]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression(
    max_iter=1000
)

lr.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [16]:
fact[
[
"payment_value",
"freight_value",
"order_value",
"item_count"
]
].isnull().sum()

payment_value      1
freight_value    775
order_value      775
item_count       775
dtype: int64

In [17]:
fact_ml = fact.dropna(
    subset=[
        "payment_value",
        "freight_value",
        "order_value",
        "item_count",
        "is_late"
    ]
)

print(fact_ml.shape)

(98665, 16)

In [18]:
fact_ml[
[
    "payment_value",
    "freight_value",
    "order_value",
    "item_count"
]
].isnull().sum()

payment_value    0
freight_value    0
order_value      0
item_count       0
dtype: int64

In [19]:
features = [
    "payment_value",
    "freight_value",
    "order_value",
    "item_count"
]

X = fact_ml[features]
y = fact_ml["is_late"]

In [20]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [21]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression(max_iter=1000)

lr.fit(X_train, y_train)

y_pred = lr.predict(X_test)
y_prob = lr.predict_proba(X_test)[:,1]

In [22]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred, zero_division=0))
print("Recall:", recall_score(y_test, y_pred, zero_division=0))
print("F1:", f1_score(y_test, y_pred, zero_division=0))
print("ROC-AUC:", roc_auc_score(y_test, y_prob))

Accuracy: 0.9337150965387929
Precision: 0.0
Recall: 0.0
F1: 0.0
ROC-AUC: 0.5624094633252918

In [23]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(
    n_estimators=200,
    random_state=42,
    class_weight="balanced"
)

rf.fit(X_train, y_train)

rf_pred = rf.predict(X_test)
rf_prob = rf.predict_proba(X_test)[:,1]

In [24]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    confusion_matrix
)

print("Accuracy:", accuracy_score(y_test, rf_pred))
print("Precision:", precision_score(y_test, rf_pred))
print("Recall:", recall_score(y_test, rf_pred))
print("F1:", f1_score(y_test, rf_pred))
print("ROC-AUC:", roc_auc_score(y_test, rf_prob))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, rf_pred))

Accuracy: 0.8426493690771804
Precision: 0.10708041958041958
Recall: 0.1874521805661821
F1: 0.13630041724617525
ROC-AUC: 0.5669372001955588

Confusion Matrix:
[[16383  2043]
 [ 1062   245]]

In [25]:
import pandas as pd

importance = pd.DataFrame({
    "Feature": features,
    "Importance": rf.feature_importances_
})

importance.sort_values(
    "Importance",
    ascending=False
)

         Feature  Importance
0  payment_value    0.338309
2    order_value    0.338223
1  freight_value    0.312986
3     item_count    0.010482

In [26]:
import pandas as pd

fact_ml = fact.dropna(
    subset=[
        "payment_value",
        "freight_value",
        "order_value",
        "item_count",
        "is_late"
    ]
).copy()

fact_ml["order_purchase_timestamp"] = pd.to_datetime(
    fact_ml["order_purchase_timestamp"]
)

fact_ml["purchase_month"] = (
    fact_ml["order_purchase_timestamp"]
    .dt.month
)

fact_ml["purchase_year"] = (
    fact_ml["order_purchase_timestamp"]
    .dt.year
)

fact_ml.head()

,order_id,customer_id,customer_city,customer_state,order_status,order_purchase_timestamp,delivery_days,delay_days,is_late,on_time_delivery,payment_value,review_score,total_price,freight_value,order_value,item_count,purchase_month,purchase_year
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,sao paulo,SP,delivered,2017-10-02 10:56:33,8.0,-8.0,0,1,38.71,4.0,29.99,8.72,38.71,1.0,10,2017
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,barreiras,BA,delivered,2018-07-24 20:41:37,13.0,-6.0,0,1,141.46,4.0,118.70,22.76,141.46,1.0,7,2018
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,vianopolis,GO,delivered,2018-08-08 08:38:49,9.0,-18.0,0,1,179.12,5.0,159.90,19.22,179.12,1.0,8,2018
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,sao goncalo do amarante,RN,delivered,2017-11-18 19:28:06,13.0,-13.0,0,1,72.20,5.0,45.00,27.20,72.20,1.0,11,2017
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,santo andre,SP,delivered,2018-02-13 21:18:39,2.0,-10.0,0,1,28.62,5.0,19.90,8.72,28.62,1.0,2,2018

In [27]:
state_dummies = pd.get_dummies(
    fact_ml["customer_state"],
    prefix="state",
    drop_first=True
)

In [28]:
base_features = fact_ml[
    [
        "payment_value",
        "freight_value",
        "order_value",
        "item_count",
        "purchase_month",
        "purchase_year"
    ]
]

X = pd.concat(
    [base_features, state_dummies],
    axis=1
)

y = fact_ml["is_late"]

print(X.shape)

(98665, 32)

In [29]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [30]:
from sklearn.ensemble import RandomForestClassifier

rf2 = RandomForestClassifier(
    n_estimators=300,
    random_state=42,
    class_weight="balanced"
)

rf2.fit(X_train, y_train)

rf2_pred = rf2.predict(X_test)
rf2_prob = rf2.predict_proba(X_test)[:,1]

In [31]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)

print("Accuracy:", accuracy_score(y_test, rf2_pred))
print("Precision:", precision_score(y_test, rf2_pred))
print("Recall:", recall_score(y_test, rf2_pred))
print("F1:", f1_score(y_test, rf2_pred))
print("ROC-AUC:", roc_auc_score(y_test, rf2_prob))

Accuracy: 0.9075153296508387
Precision: 0.1952941176470588
Recall: 0.12700841622035194
F1: 0.15391747797867408
ROC-AUC: 0.6874798351785105

In [32]:
importance = pd.DataFrame({
    "Feature": X.columns,
    "Importance": rf2.feature_importances_
})

importance.sort_values(
    "Importance",
    ascending=False
).head(15)

           Feature  Importance
2      order_value    0.234713
0    payment_value    0.234587
1    freight_value    0.224414
4   purchase_month    0.162064
5    purchase_year    0.022991
30        state_SP    0.018998
3       item_count    0.014621
23        state_RJ    0.013649
15        state_MG    0.010056
9         state_BA    0.006211
22        state_PR    0.006186
27        state_RS    0.005027
28        state_SC    0.004862
10        state_CE    0.003685
12        state_ES    0.003618